project:
  type: website
  output-dir: docs


website:
  page-navigation: true
  page-footer:
   center: "Made with ❤ by Lab25"
   border: false
   background: dark

  reader-mode: true
  title: "lab25"
  
  sidebar: 
    border: false
    logo: lab2.png
    pinned: true
    align: center
    background: dark

    tools: 
          - icon: github
            href: https://github.com/BouzasLab25
    style: "docked"
    search: true
    collapse-level: 1

    contents:
      - section: "About our laboratory"
        contents:
          - text: "Lab25"
            href: lab25.qmd

      - section: "Selected Publications"   
        contents:
          - papers.qmd
          - chapters.qmd
          - thesis.qmd

      - section: "People"
        contents:
          - arturo.qmd
          - collaborators.qmd
          - members.qmd
          - formermembers.qmd

      - section: "Educational Resources"
        contents: 
          - href: https://christian-f-badillo.github.io/Material_Apoyo_ACA_I_II_III/
            text: "Further Material 1"
          - href: https://christian-badillo.quarto.pub/aprendizaje-comportamiento-adaptable-material-de-apoyo/intro.html
            text: "Further Material 2"
          - href: https://bouzaslab25.github.io/LabVirtual25/
            text: "Virtual Lab25 Proyect"

      - text: ---------

      - section: "Archive"
        contents:  
          - text: "Old Website" 
            href: https://bouzaslab25.github.io/


fig-responsive: true
fig-format: png
      
format:
  html:
    theme: 
     dark: darkly
     light: [flatly, theme-dark.scss]
    
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: https?:\/\/(?!www\.bouzaslab25\.com(?:\/|$))[^\s"']+

    css: styles.css
 
