project:
  type: website
  output-dir: docs
  resources: 
    - img/**
    - documents/**


website:
  page-navigation: true
  page-footer:
   center: "Made with ❤ by Lab25"
   border: false
   background: dark

  reader-mode: true
  title: "lab25"
  
  sidebar: 
    border: false
    logo: img\lab25-logo.png
    pinned: true
    align: center
    background: dark

    tools: 
          - icon: github
            href: https://github.com/BouzasLab25
    style: "docked"
    search: true
    collapse-level: 1

    contents:
      - section: "About our laboratory"
        contents:
          - text: "Lab25"
            href: content\lab25.qmd

      - section: "Selected Publications"   
        contents:
          - content\papers.qmd
          - content\chapters.qmd
          - content\thesis.qmd

      - section: "People"
        contents:
          - content\arturo.qmd
          - content\collaborators.qmd
          - content\members.qmd
          - content\formermembers.qmd

      - text: "Educational Resources" # Título de la sección
      - text: ----------
      - text: "📔 Class Notes"
        href: https://arbouria.github.io/Notas-Aprendizaje-y-Comportamiento-Adaptable-I/
      - text: "🤖 Simulators 2025 "
        href: https://bouzaslab25.github.io/Material_Apoyo_ACA_I_II_III/
      - text: "💻 Simulators 2023 "
        href: https://christian-badillo.quarto.pub/aprendizaje-comportamiento-adaptable-material-de-apoyo/intro.html
      - text: "🌐 Virtual Lab25 Old Page "
        href: https://bouzaslab25.github.io/LabVirtual25/

  
      - text: ---------

      - section: "Archive"
        contents:  
          - text: "Old Website" 
            href: https://bouzaslab25.github.io/


fig-responsive: true
fig-format: png
      
format:
  html:
    theme: 
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    
    link-external-newwindow: true
    link-external-icon: true

    css: styles.css