---
title: "Recent Thesis"
---

<center> <p1>  Here are the recent thesis published by <i> Lab25 </i> </center>
</br>




+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+ 
| 📒Thesis                                                                              | Resource                                                               | 
+:======================================================================================+=======================================================================:+
| Darío Trujano Ochoa (2013), "La teoría del prospecto en la predicción de estrategias  | [PDF](http://132.248.9.195/ptd2013/noviembre/0706151/Index.html)       |    
| mixtas en un juego 2x2". (Prospect theory on the prediction of mixed strategies       |                                                                        |    
| in a 2x2 game) -B.A. in Psychology-                                                   |                                                                        |
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| José Luis Baroja Manzano (2015), "Estudios con el problema de Monty Hall"             | [PDF](http://132.248.9.195/ptd2015/abril/0727618/Index.html)           |    
| ( Studies on the Monty Hall problem ). -B.A. in Psychology-                           |                                                                        |    
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+
|  Manuel Villareal Ulloa (2017), "Transiciones en juegos 2 x 2"                        | [PDF](http://132.248.9.195/ptd2017/febrero/0756255/Index.html)         |    
|  ( Transitions on 2x2 games )  -B.A. in Psychology-                                   |                                                                        |    
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+
|  Elena Villalobos Nolasco (2017), "Estudios en Elección Intertemporal"                | [PDF](http://132.248.9.195/ptd2017/mayo/0759732/Index.html)            |    
| ( Studies on intertemporal choice ). -B.A. in Psychology-                             |                                                                        |    
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Carlos Alan Velázquez Vargas (2018), "Velocidad de cambio del entorno en el modelo    | [PDF](http://132.248.9.195/ptd2018/enero/0769970/Index.html)           |    
| clásico de reforzamiento" (Change of speed in the classical model of reinforcement ). |                                                                        | 
| -B.A. in Psychology-                                                                  |                                                                        | 
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+ 
| Jaime Osvaldo Islas Farías (2018), "Niveles cognitivos y creencias en Juegos"         | [PDF](http://132.248.9.195/ptd2018/agosto/0779927/Index.html)          |    
| ( Cognitive levels and beliefs in games ). -B.A. in Psychology-                       |                                                                        | 
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Diana Álvarez Bartolo (2019), "Estudio de la variable latente impulsividad: análisis  | [PDF](http://132.248.9.195/ptd2019/abril/0787849/Index.html)           |    
| de la definición y medición del constructo" ( Studies of the latent variable of       |                                                                        |
| impulsivity: analysis of the definition and measurement of the construct)             |                                                                        | 
| -B.A. in Psychology-                                                                  |                                                                        | 
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| José Manuel Niño García (2019), "Estudios de Transitidad en Ganancias y Pérdidas"     | [PDF](http://132.248.9.195/ptd2019/junio/0789741/Index.html)           |    
| (Studies on Transitivity within Gains and Losses ). -B.A. in Psychology-              |                                                                        | 
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Uriel Omar Gonzales Bravo (2019), "Expectativas Temporales e Invarianza escalar       | [PDF](http://132.248.9.195/ptd2019/noviembre/0798092/Index.html)       |    
| en Secuencias Asincrónicas de Estímulos" (Temporal Expectations and Scalar            |                                                                        |
| Invariance in Isochronic Sequences of Stimuli)                                        |                                                                        | 
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Norma Karina Ruíz García (2021), " Estudios sobre el efecto de Framing.Compatibilidad | [PDF](http://132.248.9.195/ptd2021/mayo/0811875/Index.html)            |
| en el Lenguaje" (Studies on the effect of Framed. compatibility in lenguague)         |                                                                        |
| - B.A in psychology -                                                                 |                                                                        |
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Melisa Eréndira Chávez Guerrero (2022) " Elección intertemporal Compensando magnitud  | [PDF](http://132.248.9.195/ptd2022/abril/0824767/Index.html)           |
| y demora (Intertemporary election: Compensanting Magnitude and delay")                |                                                                        |
| - PhD in psychology -                                                                 |                                                                        |
+---------------------------------------------------------------------------------------+------------------------------------------------------------------------+